docker run -it -d  \
  --label traefik.http.routers.bamicomicrofinance.rule=Host\(\`bamicomicrofinance.phamasoft.com\`\) \
  --label traefik.http.routers.bamicomicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.bamicomicrofinance.tls=true \
  --label traefik.http.routers.bamicomicrofinance.service=bamicomicrofinance-http \
  --label traefik.http.services.bamicomicrofinance-http.loadbalancer.server.port=80 \
  --name bamicomicrofinance \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft:may13